### ISSUE TITLE
[bug] can not find package.json

### ISSUE THREAD

**Issue by Delaube923** [Kelvin-1013/solana-jito-pumpfun-mevbot#1]
when i run npm install ,it's can't find package.json
![20241027-183029](https://github.com/user-attachments/assets/e2db415e-a5ec-4787-b505-7524261b0c63)

**Comment by Kelvin-1013** [comment]
First of all, run `npm init`
Find *.js file in this project (find in test folder) and you can see require ('node module').
Run `npm install`
This case [solana-jito-pumpfun-mevbot](https://github.com/Kelvin-1013/solana-jito-pumpfun-mevbot)
 is 100 % rust language.
 You don't have to run `npm install`, just run `cargo build`
